global_costmap:  
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 1.0
    publish_frequency: 0 
    static_map: true 
    rolling_window: false 
    width: 30.0
    height: 110.0
    resolution: 0.02
    transform_tolerance: 1.0
    map_type: costmap 

GlobalPlanner:
    allow_unknown: false