shutdown_costmaps: false

controller_frequency: 4.0 #before 5.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 3.0

oscillation_timeout: 5.0
oscillation_distance: 0.2

#conservative_reset_dist: 0.1 #distance from an obstacle at which it will unstuck itself

#cost_factor: 0.55
#neutral_cost: 66 
#lethal_cost: 253

max_planning_retires: 1

recovery_behavior_enabled: true
clearing_rotation_allowed: true

recovery_behaviors:
    - name: 'conservative_reset'
      type: 'clear_costmap_recovery/ClearCostmapRecovery'
    - name: 'clearing_rotation'
      type: 'rotate_recovery/RotateRecovery'

conservative_reset:
    reset_distance: 1.0
    layer_names: [obstacle_layer]

aggressive_reset:
    reset_distance: 3.0
    layer_names: [obstacle_layer]

super_reset:
    reset_distance: 5.0
    layer_names: [obstacle_layer]

move_slow_and_clear:
    clearing_distance: 0.5
    limited_trans_speed: 1.25
    limited_rot_speed: 1.25
    limited_distance: 0.3