local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 0.3

  static_map: false  
  rolling_window: true
  width: 20
  height: 100
  resolution: 0.07
  
